version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user_example
      POSTGRES_PASSWORD: pass_example
      POSTGRES_DB: db_example
    ports:
      - 5432:5432
  app:
    build: .
    command: go run main.go
    environment: 
      EXAMPLEENV: local